_security_login:
  pattern: /login
  defaults: { _controller: PublilingusAdminBundle:Admin:login }

_security_check:
  pattern: /login_check

_security_logout:
    pattern: /logout

homepage:
    resource: "@PublilingusPubliBundle/Controller"
    type: annotation

admin:
    resource: "@PublilingusAdminBundle/Controller"
    type: annotation
